version: '2'
x-restart-policy: &restart-policy "no"
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    restart: always
    ports:
      - 192.168.9.104:53:53/udp
      - 192.168.9.104:53:53/tcp

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: *restart-policy
#    ports:
#      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    restart: always
    ports:
      - 192.168.9.104:80:80/tcp
      - 192.168.9.104:444:444/tcp
    volumes:
      - /RSP0/docker/volumes/lancache/cache:/data/cache
      - /RSP0/docker/volumes/lancache/logs:/data/logs
