version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - /home/g6seven/Documents/dev/dockerEnv/volumes/joplin-server/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=Your-Password-here
      - POSTGRES_USER=joplin-user
      - POSTGRES_DB=joplindb
  app:
    image: joplin/server:latest
    container_name: joplin-server
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      - APP_PORT=8080
      - APP_BASE_URL=http://localhost:8080
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=Your-Password-here
      - POSTGRES_DATABASE=joplindb
      - POSTGRES_USER=joplin-user
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
