version: '3'

services:
    filecloud.mongodb:
        restart: unless-stopped 
        container_name: 'filecloud.mongodb'
        image: mongo:6.0.8
        environment:
            - mongodb_data_container=/data/db
        volumes:
            - mongo_database:/data/db

    filecloud.server:
        restart: unless-stopped
        container_name: 'filecloud.server'
        image: filecloud/filecloudserver23.1:latest
        depends_on:
            - filecloud.mongodb
            - filecloud.preview
        volumes:
            - cloud_data:/var/clouddata
            - var_html:/var/www/html
        links:
            - filecloud.mongodb
        ports:
            - "192.168.9.106:80:80"
            - "192.168.9.106:443:443"

    filecloud.preview:
        restart: unless-stopped
        container_name: 'filecloud.preview'
        image: filecloud/filecloudpreview22.1:latest
        volumes:
            - cloud_data:/var/clouddata
            - var_html:/var/www/html

    filecloud.solr:
        restart: unless-stopped
        container_name: 'filecloud.solr'
        image: filecloud/filecloudsolr21.3:latest
        volumes:
            - solr_data:/var/solr
            - var_html:/var/www/html

volumes:
    mongo_database:
        driver: local
        driver_opts: 
          type: opts
          o: bind
          device: /RSP0/docker/filecloud/mongo_database
    cloud_data:
        driver: local
        driver_opts:
          type: opts
          o: bind
          device: /RSP0/docker/filecloud/cloud_data
    solr_data:
        driver: local
        driver_opts:
          type: opts
          o: bind
          device: /RSP0/docker/filecloud/solr_data
    var_html:
        driver: local
        driver_opts:
          type: opts
          o: bind
          device: /RSP0/docker/filecloud/var_html
