services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      USER: "g6seven"
      PASS: "changeme"
    ports:
      - 192.168.9.101:445:445
    volumes:
      - /RSP0:/RSP0
      - /RSP0/yaml/samba-server/smb.conf:/etc/samba/smb.conf:ro
